name: Obtener reporte diario
on:
  schedule:
  - cron: "50 0-4/2,16-23/2 * * *"
  workflow_dispatch:

jobs:
  reporte_diario:
    runs-on: windows-latest
    name: Obtener reporte diario

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: '13'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Script
        run: python3 ./src/main.py
        
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: "información desde reporte diario"
